#! /bin/sh

picom -b &
feh --bg-fill /usr/share/background/archlinux/archwave.png
wmname LG3D &
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config normal_border_color "#f93984"
bspc config active_border_color "#f93984"
bspc config presel_feedback_color "#f93984"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
